# Generated by Django 5.2 on 2025-06-01 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='テンプレート側で使うキー', max_length=100, unique=True)),
                ('message', models.TextField(help_text='表示するメッセージ本文（html可）')),
                ('is_active', models.BooleanField(default=True, help_text='有効フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='ErrLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('INFO', 'info'), ('WARNING', 'warning'), ('ERROR', 'error'), ('CRITICAL', 'critical')], max_length=50)),
                ('module', models.CharField(blank=True, help_text='エラーが発生した機能や画面名', max_length=255)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, help_text='詳細なトレース（あれば）')),
                ('resolved', models.BooleanField(default=False, help_text='解決済みフラグ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
